version: '1'
services:

  elasticsearch:
    image: centos:7
    ports:
    - 9200:9200
    expose:
    - 9200
    - 9300
    restart: always
    user: elasticsearch
    working_dir: /usr/share/elasticsearch/bin
    command: [./elasticsearch]
    options:
      openshift:
        replicas: 3

    #volumes:
    #- your_volume:/usr/share/elasticsearch/data
    #- your_volume:/usr/share/elasticsearch/logs
    #- your_volume:/usr/share/elasticsearch/config

  logstash:
    image: centos:7
    ports:
    - 5044:5044
    links:
    - elasticsearch
    restart: always
    working_dir: /opt/logstash/bin
    command: [./logstash, agent, -f, /etc/logstash/conf.d]
    environment:
    - JAVACMD=/usr/bin/java
    entrypoint: ["/usr/bin/entrypoint.sh"]

    #volumes:
    #- your_configuration_volume:/etc/logstash/conf.d

  kibana:
    image: centos:7
    ports:
    - 5601:5601
    expose:
      - 5601
    user: kibana
    links:
    - elasticsearch
    working_dir: /opt/kibana/bin
    command: [./kibana]

registries: {}
