- hosts: elasticsearch
  roles:
  - role: elasticsearch-container
    elasticsearch_network_host: 0.0.0.0
    elasticsearch_discovery_hosts: ['elasticsearch']
    elasticsearch_http_port: 9200
    elasticsearch_script_inline: 1
    elasticsearch_script_indexed: 1
    elasticsearch_data: /usr/share/elasticsearch/data
    elasticsearch_logs: /usr/share/elasticsearch/logs
    elasticsearch_config: /usr/share/elasticsearch/config
    java_home: ''
    java_packages:
      - java-1.8.0-openjdk


- hosts: logstash
  roles:
  - role: chouseknecht.logstash-container
    logstash_elasticsearch_hosts:
    - http://elasticsearch:9200
    logstash_listen_port_beats: 5044
    logstash_local_syslog_path: /var/log/syslog
    logstash_monitor_local_syslog: true
    logstash_ssl_dir: /etc/pki/logstash
    logstash_ssl_certificate_file: ''
    logstash_ssl_key_file: ''
    logstash_enabled_on_boot: yes
    logstash_install_plugins:
    - logstash-input-beats

  # Set create_example to 'true', if sameple data should be loaded
  #  into apache_elastic_example index. 
  - role: create_example
    create_example: false
 
- hosts: kibana
  roles:
  - role: kibana-container
    kibana_host: 0.0.0.0
    kibana_port: 5601
    kibana_elasticsearch_url: http://elasticsearch:9200
    kibana_index: .kibana
    kibana_log_dest: stdout
    kibana_logging_silent: false
    kibana_logging_quiet: false
    kibana_logging_verbose: true

  
